#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';

const root='/home/li/primary';
const base=path.join(root,'flows/5f38bc/psyche-fable-refresh');
const session='messaging-build';
const [pane,terminal]=process.argv.slice(2);
if(process.env.HERDR_ENV!=='1') throw new Error('must run in the fresh Herdr pane');
if(!pane||!terminal) throw new Error('pane and terminal required');
const run=(bin,args)=>execFileSync(bin,args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','pipe']});
const json=(args)=>JSON.parse(run('herdr',['--session',session,...args])).result;
const write=(name,value)=>fs.writeFileSync(path.join(base,name),JSON.stringify(value,null,2)+'\n',{mode:0o600});
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const now=()=>new Date().toISOString();
const profile=JSON.parse(fs.readFileSync(path.join(base,'profile.json'),'utf8'));
const source=profile.sources[0];
if(hash(path.join(root,source.path))!==source.sha256) throw new Error('reviewed source bundle changed');
const existing=json(['agent','list']).agents??[];
if(existing.some(a=>a.name==='psyche-fable-refresh-5f38bc')) throw new Error('fresh Fable name already exists');
const self=json(['pane','get',pane]).pane;
if(self?.terminal_id!==terminal||self?.workspace_id!=='wD'||path.resolve(self?.cwd??'')!==root) throw new Error('fresh target pane binding differs');
const priorPath=path.join(base,'prestart.json');
const prior=fs.existsSync(priorPath)?JSON.parse(fs.readFileSync(priorPath,'utf8')):null;
const thread=prior?.thread??crypto.randomUUID();
const claim=prior?.claim??run('flow-id',['claude','--flows-root',path.join(root,'flows'),'--parent-session',thread]).trim();
if(!/^[a-f0-9]{6}$/.test(claim)) throw new Error(`unexpected claimed flow id: ${claim}`);
const flowRoot=path.join(root,'flows',claim);
fs.mkdirSync(flowRoot,{recursive:true});
const title=prior?.title??`Psyche Fable ${claim}`;
const prompt=prior?.prompt??`/main-flow /refresh Flow ID is ${claim}. Read flows/752e0f/refresh-bundle.md in full now.`;
if(/[\r\n]/.test(prompt) || !prompt.startsWith('/main-flow /refresh ')) throw new Error('startup argument is not one physical line with the required leading skills');
const jobDir=path.join(process.env.HOME,'.claude','jobs',`native-${thread}`);
if (!fs.existsSync(jobDir)) fs.mkdirSync(jobDir,{recursive:false,mode:0o700});
else if (fs.readdirSync(jobDir).length!==0) throw new Error('reserved job directory gained state');
const envMarker=`CLAUDE_ENV_READY_${thread}_${crypto.randomBytes(12).toString('hex')}`;
const shell=`unset CLAUDE_CODE_CHILD_SESSION CLAUDE_CODE_SESSION_KIND CLAUDE_CODE_SESSION_ID && export CLAUDE_JOB_DIR='${jobDir}' && printf '%s\\n' '${envMarker}'`;
write('prestart.json',{at:now(),profile,sourceHash:source.sha256,session,workspace:'wD',pane,terminal,thread,claim,title,prompt,argv:['claude','--session-id',thread,'--model',profile.model,'--effort',profile.effort,'--name',title,'--remote-control','--dangerously-skip-permissions','--system-prompt-file',path.join(root,'tools/main-flow-mode/system-prompt.md'),prompt]});
run('herdr',['--session',session,'pane','run',pane,shell]);
const waited=json(['pane','wait-output',pane,'--match',envMarker,'--source','visible','--lines','50','--timeout','5000']);
if(waited?.matched_line!==envMarker) throw new Error('environment preparation marker absent');
const start=json(['agent','start','psyche-fable-refresh-5f38bc','--kind','claude','--pane',pane,'--timeout','300000','--','--session-id',thread,'--model',profile.model,'--effort',profile.effort,'--name',title,'--remote-control','--dangerously-skip-permissions','--system-prompt-file',path.join(root,'tools/main-flow-mode/system-prompt.md'),prompt]);
const agent=start.agent??json(['agent','get','psyche-fable-refresh-5f38bc']).agent;
if(agent?.name!=='psyche-fable-refresh-5f38bc'||agent?.pane_id!==pane||agent?.terminal_id!==terminal||agent?.interactive_ready!==true) throw new Error('Herdr agent readiness/binding differs');
const proc=json(['pane','process-info','--pane',pane]).process_info;
const match=(proc?.foreground_processes??[]).filter(p=>{const i=(p.argv??[]).indexOf('--session-id'); return i>=0&&p.argv[i+1]===thread;});
if(match.length!==1) throw new Error('native process identity is not unique');
const environ=Object.fromEntries(fs.readFileSync(`/proc/${match[0].pid}/environ`,'utf8').split('\0').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1)]}));
if(environ.CLAUDE_JOB_DIR!==jobDir || 'CLAUDE_CODE_CHILD_SESSION' in environ || 'CLAUDE_CODE_SESSION_KIND' in environ) throw new Error('child session isolation failed');
write('launch.json',{at:now(),phase:'started',profileSha256:hash(path.join(base,'profile.json')),bundleSha256:source.sha256,session,workspace:'wD',agent:agent.name,pane,terminal,thread,flowId:claim,title,prompt,process:{pid:match[0].pid,jobDir},startResult:start});
console.log(JSON.stringify({phase:'started',flowId:claim,thread,agent:agent.name,pane,terminal,title,prompt},null,2));
