[package]
name = "disk-situation-report"
version = "0.1.0"
edition = "2021"

[dependencies]
datom-codec = { git = "https://github.com/LiGoldragon/datom-codec.git", rev = "6dccc76b75918a91d3370a9d4fe88aa7dd567876" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

protos = { git = "https://github.com/LiGoldragon/protos", rev = "171b21f65337983ab624b7b906397a4f1f92c5a3" }
