import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import {injectRouting, main, makeProxy} from './provider-run.mjs';

const messages = [{role: 'user', content: 'keep this exact'}];
const original = {model: 'moonshotai/kimi-k3', messages};
const routed = injectRouting(original, {routing: {provider: {only: ['Fireworks'], allow_fallbacks: false}}});
assert.deepEqual(routed.provider, {only: ['Fireworks'], allow_fallbacks: false});
assert.deepEqual(routed.messages, messages);
assert.notEqual(routed.messages, messages);
const here = path.dirname(new URL(import.meta.url).pathname);
const fireworks = JSON.parse(fs.readFileSync(path.join(here, 'fixtures/fireworks.json')));
const fallback = JSON.parse(fs.readFileSync(path.join(here, 'fixtures/openrouter-fireworks-pinned.json')));
assert.deepEqual(Object.keys(fireworks).sort(), ['access_authorized','baseURL','expected_opencode_version','model','provider','version']);
assert.equal(fireworks.access_authorized, false);
assert.equal(fireworks.provider, 'fireworks');
assert.equal(fireworks.baseURL, 'https://api.fireworks.ai/inference/v1');
assert.equal(fireworks.model, 'accounts/fireworks/models/kimi-k3');
assert.equal(fallback.access_authorized, false);
assert.equal(fallback.provider, 'openrouter-fireworks-pinned');
assert.deepEqual(fallback.routing.provider, {only:['Fireworks'],allow_fallbacks:false});
const fake = path.join(os.tmpdir(), `third-seat-no-network-${process.pid}`);
fs.writeFileSync(fake, '#!/bin/sh\nexit 99\n', {mode:0o755});
await assert.rejects(main(['--provider-descriptor',path.join(here,'fixtures','fireworks.json'),'--secret-fd','3','--opencode',fake,'--output',path.join(here,'fixtures','ignored-output')]), /access_authorized/);
fs.rmSync(fake);
let forwarded;
const proxy = await makeProxy(new URL('https://fixture.invalid/v1'), 'inert-local-secret', undefined, async (_upstream, secret, body) => { forwarded = {secret, body:JSON.parse(body)}; return {status:503,type:'application/json',body:Buffer.from('inert-local-secret')}; }, fallback);
const url = new URL(proxy.url + '/chat/completions');
const refusal = await new Promise((resolve,reject) => { const req=http.request({host:url.hostname,port:url.port,path:url.pathname,method:'POST'},res => { let text='';res.on('data',b=>text+=b);res.on('end',()=>resolve({status:res.statusCode,text})); }); req.on('error',reject); req.end(JSON.stringify(original)); });
const latched = await new Promise((resolve,reject) => { const req=http.request({host:url.hostname,port:url.port,path:url.pathname,method:'POST'},res => { res.resume();res.on('end',()=>resolve(res.statusCode)); }); req.on('error',reject); req.end(JSON.stringify(original)); });
await proxy.close();
assert.equal(forwarded.secret, 'inert-local-secret');
assert.deepEqual(forwarded.body.messages, messages);
assert.deepEqual(forwarded.body.provider, {only:['Fireworks'],allow_fallbacks:false});
assert.deepEqual([refusal.status,latched], [502,502]);
assert.doesNotMatch(refusal.text, /inert-local-secret/);
console.log('provider route injection test passed');
