[workspace]
resolver = "3"
members = ["nexus-entry", "chronos-toy", "chronos-generated"]

[workspace.dependencies]
kameo = { version = "0.22", default-features = false, features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "sync"] }
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
