[package]
name    = "horizon-lib"
version = "0.10.1"
edition = "2024"
build = "build.rs"
autotests = false

[features]
default = ["datom"]
datom = ["dep:datom-codec", "dep:protos"]

[dependencies]
serde      = { workspace = true }
protos = { workspace = true, optional = true }
datom-codec = { workspace = true, optional = true }
rkyv = { version = "0.8", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }
thiserror  = { workspace = true }

[build-dependencies]
ethos-zero = { workspace = true }

[[test]]
name = "contract"
path = "tests/contract.rs"
