import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';

const d=fs.mkdtempSync(path.join(os.tmpdir(),'component-evidence-'));
const root=path.join(d,'repos'); fs.mkdirSync(root);
const repo=path.join(root,'alpha'); fs.mkdirSync(repo); fs.mkdirSync(path.join(repo,'.jj'));
fs.symlinkSync(repo,path.join(root,'alpha-alias'),'dir');
fs.mkdirSync(path.join(root,'not-a-repo'));
const manifest=path.join(d,'manifest');
fs.writeFileSync(manifest,'(Repo alpha github:LiGoldragon/alpha (Family Test) Code Active Architecture [])\n');
const inputs=path.join(d,'inputs');
fs.writeFileSync(inputs,'{"alpha":{"unit":"alpha-daemon.service","witness":{"ref":"fixture-witness","date":"2026-09-14","scope":"fixture","result":"pass"},"review":{"ref":"fixture-review","date":"2026-09-14","scope":"fixture","result":"accepted"}}}');
const fakeBin=path.join(d,'bin'); fs.mkdirSync(fakeBin);
const fakeJj=path.join(fakeBin,'jj');
fs.writeFileSync(fakeJj,'#!/bin/sh\nprintf "fixture-revision fixture commit\\n"\n'); fs.chmodSync(fakeJj,0o755);
const fakeSystemctl=path.join(fakeBin,'systemctl');
fs.writeFileSync(fakeSystemctl,'#!/bin/sh\nprintf "LoadState=loaded\\nActiveState=active\\nSubState=running\\nExecStart={ /nix/store/fake/bin/alpha --secret hidden ; pid=1\\n"\n'); fs.chmodSync(fakeSystemctl,0o755);
const env={...process.env,REPO_ROOT:root,REPO_MANIFEST:manifest,COMPONENT_EVIDENCE_INPUTS:inputs,COMPONENT_EVIDENCE_JJ:fakeJj,COMPONENT_EVIDENCE_SYSTEMCTL:fakeSystemctl};
const inv=JSON.parse(execFileSync('./tools/repo-inventory',{env,encoding:'utf8'}));
assert.equal(inv.rows.length,1); assert.equal(inv.discovered.length,0); assert.deepEqual(inv.aliases[0].names.sort(),['alpha','alpha-alias']);
const evidence=JSON.parse(execFileSync('./tools/component-evidence',{env,encoding:'utf8'}));
assert.equal(evidence.components[0].bounded_witness.ref,'fixture-witness');
assert.equal(evidence.components[0].source_revision.value,'fixture-revision fixture commit');
assert.deepEqual(evidence.components[0].deployed_executable,{unit:'alpha-daemon.service',load_state:'loaded',active_state:'active',sub_state:'running',executable:'/nix/store/fake/bin/alpha'});
assert.equal(JSON.stringify(evidence).includes('secret'),false);
const off=JSON.parse(execFileSync('./tools/component-evidence',{env:{...env,COMPONENT_EVIDENCE_SYSTEMCTL:'off'},encoding:'utf8'}));
assert.equal(off.components[0].deployed_executable.status,'unknown');
const missing=path.join(d,'missing-manifest'); fs.writeFileSync(missing,'(Repo beta github:LiGoldragon/beta (Family Test) Code Active Architecture [])\n');
const m=JSON.parse(execFileSync('./tools/repo-inventory',{env:{...env,REPO_MANIFEST:missing},encoding:'utf8'}));
assert.equal(m.missing[0].status,'missing-locally');
console.log('component evidence fixtures passed');
