import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {decide,deregisterInvocation,markerCandidate,typedSnapshot} from './field-luna-heartbeat.mjs';
const d=fs.mkdtempSync(path.join(os.tmpdir(),'field-luna-test-')), evidence=path.join(d,'evidence'); fs.writeFileSync(evidence,'retained');
const sha=crypto.createHash('sha256').update('retained').digest('hex'), record={session:'s',name:'n',pane_id:'p',terminal_id:'t',agent:'codex'}, marker={version:1,state:'retired',flow:'abc123',record,native_thread:'01234567-0000-4000-8000',evidence:{path:evidence,sha256:sha}};
const route={...record,native_thread:marker.native_thread,state:'Bound'};
const snapshot=typedSnapshot({status:0,stdout:JSON.stringify({version:1,routes:[{flow:'abc123',route}],retirements:[marker]})});
const c=markerCandidate(snapshot.retirements[0],new Map(snapshot.routes.map(({flow,route})=>[flow,route]))); assert.equal(decide(c,{agent:{agent_status:'working'},locks:'',pane:record}),'hold-agent-not-done'); assert.equal(decide(c,{agent:{agent_status:'done'},locks:'abc123',pane:record}),'hold-active-lock'); assert.equal(decide(c,{agent:{agent_status:'done'},locks:'',pane:record}),'eligible');
assert.deepEqual(deregisterInvocation(c),['hm-deregister',['abc123','--name','n','--session','s','--pane-id','p','--terminal-id','t']]);
assert.equal(markerCandidate(marker,new Map()).state,'already-deregistered');
assert.throws(()=>typedSnapshot({status:0,stdout:JSON.stringify({version:1,routes:[{flow:'abc123',route:{}}],retirements:[]})}),/invalid typed HM route/);
assert.throws(()=>typedSnapshot({status:1,stdout:''}),/typed HM state unavailable/);
fs.rmSync(d,{recursive:true,force:true}); console.log('field Luna heartbeat typed fixtures passed');
