import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {decide,markerCandidate} from './field-luna-heartbeat.mjs';
const d=fs.mkdtempSync(path.join(os.tmpdir(),'field-luna-test-')), evidence=path.join(d,'evidence'); fs.writeFileSync(evidence,'retained');
const sha=crypto.createHash('sha256').update('retained').digest('hex'), record={session:'s',name:'n',pane_id:'p',terminal_id:'t',agent:'codex'}, marker={version:1,state:'retired',flow:'abc123',record,native_thread:'01234567-0000-4000-8000',evidence:{path:evidence,sha256:sha}};
fs.mkdirSync(path.join(d,'retired')); fs.writeFileSync(path.join(d,'retired','abc123.json'),JSON.stringify(marker)); fs.writeFileSync(path.join(d,'abc123.json'),JSON.stringify({...record,native_thread:marker.native_thread}));
const c=markerCandidate(path.join(d,'retired','abc123.json'),d); assert.equal(decide(c,{agent:{agent_status:'working'},locks:'',pane:record}),'hold-agent-not-done'); assert.equal(decide(c,{agent:{agent_status:'done'},locks:'abc123',pane:record}),'hold-active-lock'); assert.equal(decide(c,{agent:{agent_status:'done'},locks:'',pane:record}),'eligible'); fs.rmSync(d,{recursive:true,force:true}); console.log('field Luna heartbeat fixtures passed');
