#!/usr/bin/env node
import assert from 'node:assert/strict';
import path from 'node:path';
import {dispatchCommand, parseArgs} from './native-voice-launch.mjs';
const field = parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md', '--predecessor', 'abcdef']);
assert.deepEqual(field, {aspect: 'Field', layer: 'Primary', brief: '/tmp/field.md', root: false, predecessor: 'abcdef', metaflow: undefined, topic: undefined});
const command = dispatchCommand(field);
assert.equal(command.command, process.execPath);
assert.deepEqual(command.args.slice(-8), ['--aspect', 'Field', '--layer', 'Primary', '--brief', '/tmp/field.md', '--predecessor', 'abcdef']);
assert.match(command.args[0], /codex-main-flow-launch\.mjs$/);
const root = parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md', '--root', '--metaflow', '/tmp/metaflow.datom']);
assert.deepEqual(dispatchCommand(root).args.slice(-9), ['--aspect', 'Field', '--layer', 'Primary', '--brief', '/tmp/field.md', '--root', '--metaflow', '/tmp/metaflow.datom']);
const topicRoot = parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md', '--root', '--metaflow', '/tmp/metaflow.datom', '--topic', 'Ethos']);
assert.deepEqual(dispatchCommand(topicRoot).args.slice(-11), ['--aspect', 'Field', '--layer', 'Primary', '--brief', '/tmp/field.md', '--root', '--metaflow', '/tmp/metaflow.datom', '--topic', 'Ethos']);
assert.throws(() => parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md', '--root', '--metaflow', '/tmp/metaflow.datom', '--topic', 'ethos-zero']), /dense PascalCase/);
assert.throws(() => parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md', '--predecessor', 'abcdef', '--topic', 'Ethos']), /--topic is only valid with --root/);
assert.throws(() => parseArgs(['--voice', 'Field.Primary', '--brief', '/tmp/field.md']), /usage/);
assert.throws(() => parseArgs(['--voice', 'Field.Primary']), /usage/);
assert.throws(() => dispatchCommand(parseArgs(['--voice', 'Mind.Secondary', '--brief', '/tmp/mind.md', '--predecessor', 'abcdef'])), /correspondence is pending/);
console.log('native-voice-launch tests passed');
