import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { deliverFanout, planFanout } from './prompt-fanout-core.mjs';

const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'prompt-fanout-'));
const source = path.join(directory, 'fixture.jsonl');
const text = 'éééééé exact bytes ΩΩΩΩΩΩ';
fs.writeFileSync(source, JSON.stringify({ type: 'user', uuid: 'message-17', origin: { kind: 'human' }, timestamp: '2026-09-15T00:00:00.000Z', message: { role: 'user', content: text } }));
let reads = 0;
const plan = planFanout({ source, match: 'éééééé..ΩΩΩΩΩΩ', sourceId: 'message-17', sourceKind: 'human', bodyMode: 'whole', endpoints: ['codex:thread-17@opaque', 'claude:session-17@opaque'], read: (...args) => { reads += 1; return fs.readFileSync(...args); } });
assert.equal(reads, 1);
assert.equal(plan.provenance.source_message_id, 'message-17');
assert.equal(plan.endpoints.length, 2);
assert.strictEqual(plan.endpoints[0].bytes, plan.bytes);
assert.strictEqual(plan.endpoints[1].bytes, plan.bytes);
assert.equal(plan.endpoints[0].bytes.toString('utf8'), text);
assert.equal(plan.provenance.sha256_utf8, '8232a27b1084ed8d3db2518653906b999e0b04697aa39965d705b134c830087f');
const deliveries = [];
const whole = deliverFanout({ plan, adapters: { codex: item => deliveries.push(item), claude: item => deliveries.push(item) } });
assert.deepEqual(whole.map(item => item.status), ['delivered', 'delivered']);
assert.strictEqual(deliveries[0].bytes, plan.bytes);
assert.strictEqual(deliveries[1].bytes, plan.bytes);
const receiptPlan = { ...plan, bodyMode: 'receipt' };
const receipts = [];
const receipt = deliverFanout({ plan: receiptPlan, adapters: { codex: item => receipts.push(item), claude: item => receipts.push(item) } });
assert.deepEqual(receipt.map(item => item.status), ['delivered', 'delivered']);
assert.notStrictEqual(receipts[0].bytes, plan.bytes);
assert.strictEqual(receipts[0].bytes, receipts[1].bytes);
assert.match(receipts[0].bytes.toString('utf8'), /fanout-receipt/);
assert.doesNotMatch(receipts[0].bytes.toString('utf8'), new RegExp(text));
const failed = deliverFanout({ plan, adapters: { codex: () => { throw new Error('mock codex failure'); }, claude: () => { throw new Error('mock claude failure'); } } });
assert.deepEqual(failed.map(item => item.status), ['failed', 'failed']);
assert.match(failed[0].error, /mock codex failure/);
const assistantSource = path.join(directory, 'assistant.jsonl');
const assistantText = 'final! assistant delivery payload!';
fs.writeFileSync(assistantSource, JSON.stringify({ type: 'event_msg', timestamp: '2026-09-15T00:01:00.000Z', payload: { type: 'item_completed', item: { type: 'AgentMessage', id: 'assistant-final-17', content: assistantText } } }));
const assistant = planFanout({ source: assistantSource, match: 'final!..yload!', sourceId: 'assistant-final-17', sourceKind: 'assistant-final', bodyMode: 'whole', endpoints: ['codex:thread-17@opaque'] });
assert.equal(assistant.provenance.source_format, 'codex-assistant-final');
assert.throws(() => planFanout({ source, match: 'éééééé..ΩΩΩΩΩΩ', sourceKind: 'human', bodyMode: 'whole', endpoints: ['codex:x@opaque'] }), /source-id/);
const output = JSON.parse(execFileSync(process.execPath, [path.join(import.meta.dirname, 'prompt-fanout'), 'plan', '--source', source, '--match', 'éééééé..ΩΩΩΩΩΩ', '--source-id', 'message-17', '--source-kind', 'human', '--body-mode', 'receipt', '--endpoint', 'codex:thread-17@opaque'], { encoding: 'utf8' }));
assert.equal(output.kind, 'fanout-plan');
assert.equal(output.body_mode, 'receipt');
assert.equal(output.provenance.source_message_id, 'message-17');
assert.equal(output.raw_text_bytes, Buffer.byteLength(text));
console.log('prompt-fanout fixtures passed');
